//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amenity()
        {
            this.PropertyAmenities = new HashSet<PropertyAmenity>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Breakfast { get; set; }
        public Nullable<bool> AirConditioner { get; set; }
        public Nullable<bool> Lunch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAmenity> PropertyAmenities { get; set; }
    }
}
