//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingStatu()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
