//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumProje_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string CVV { get; set; }
    
        public virtual User User { get; set; }
    }
}
